---
- name: Deploy Maven Artifact
  hosts: local
  tasks:
    - name: Copy the artifact to the deployment directory
      copy:
        src: "/var/lib/jenkins/workspace/HelloMaven-CI/target/HelloMaven-CI-1.0-SNAPSHOT.jar"
        dest: "/opt/deployment/HelloMaven-CI.jar"
